-- MySQL Script generated by MySQL Workbench
-- Sat Aug 29 11:20:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `apprenant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apprenant` (
  `idApprenant` INT NOT NULL AUTO_INCREMENT,
  `nomApprenant` VARCHAR(50) NOT NULL,
  `prenomApprenant` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `mot_de_passe` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idApprenant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cours` (
  `idCours` INT NOT NULL AUTO_INCREMENT,
  `plateforme_url` VARCHAR(100) NOT NULL,
  `nomCours` VARCHAR(200) NOT NULL,
  `id_apprenant_plateforme` INT NOT NULL,
  PRIMARY KEY (`idCours`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trace` (
  `idTrace` INT NOT NULL AUTO_INCREMENT,
  `nomTrace` VARCHAR(100) NOT NULL,
  `debut` DATETIME(6) NOT NULL,
  `fin` DATETIME(6) NOT NULL,
  `apprenant_idApprenant` INT NOT NULL,
  `cours_idCours` INT NOT NULL,
  PRIMARY KEY (`idTrace`),
  INDEX `fk_trace_apprenant1_idx` (`apprenant_idApprenant` ASC),
  INDEX `fk_trace_cours1_idx` (`cours_idCours` ASC),
  CONSTRAINT `fk_trace_apprenant1`
    FOREIGN KEY (`apprenant_idApprenant`)
    REFERENCES `apprenant` (`idApprenant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trace_cours1`
    FOREIGN KEY (`cours_idCours`)
    REFERENCES `cours` (`idCours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indicateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indicateur` (
  `nomIndicateur` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`nomIndicateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `strategie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strategie` (
  `idStratégie` INT NOT NULL AUTO_INCREMENT,
  `nomStrategie` VARCHAR(100) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `indicateur_nomIndicateur` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idStratégie`, `indicateur_nomIndicateur`),
  INDEX `fk_strategie_indicateur1_idx` (`indicateur_nomIndicateur` ASC),
  CONSTRAINT `fk_strategie_indicateur1`
    FOREIGN KEY (`indicateur_nomIndicateur`)
    REFERENCES `indicateur` (`nomIndicateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `suggestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suggestion` (
  `idSuggestion` INT NOT NULL AUTO_INCREMENT,
  `description_suggestion` VARCHAR(200) NOT NULL,
  `indicateur_nomIndicateur` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idSuggestion`),
  INDEX `fk_suggestion_indicateur1_idx` (`indicateur_nomIndicateur` ASC),
  CONSTRAINT `fk_suggestion_indicateur1`
    FOREIGN KEY (`indicateur_nomIndicateur`)
    REFERENCES `indicateur` (`nomIndicateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cours_has_suggestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cours_has_suggestion` (
  `cours_idCours` INT NOT NULL,
  `suggestion_idSuggestion` INT NOT NULL,
  PRIMARY KEY (`cours_idCours`, `suggestion_idSuggestion`),
  INDEX `fk_cours_has_suggestion_suggestion1_idx` (`suggestion_idSuggestion` ASC),
  INDEX `fk_cours_has_suggestion_cours1_idx` (`cours_idCours` ASC),
  CONSTRAINT `fk_cours_has_suggestion_cours1`
    FOREIGN KEY (`cours_idCours`)
    REFERENCES `cours` (`idCours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cours_has_suggestion_suggestion1`
    FOREIGN KEY (`suggestion_idSuggestion`)
    REFERENCES `suggestion` (`idSuggestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objectif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objectif` (
  `apprenant_idApprenant` INT NOT NULL,
  `cours_idCours` INT NOT NULL,
  `description_objectif` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`apprenant_idApprenant`, `cours_idCours`),
  INDEX `fk_apprenant_has_cours_cours1_idx` (`cours_idCours` ASC),
  INDEX `fk_apprenant_has_cours_apprenant1_idx` (`apprenant_idApprenant` ASC),
  CONSTRAINT `fk_apprenant_has_cours_apprenant1`
    FOREIGN KEY (`apprenant_idApprenant`)
    REFERENCES `apprenant` (`idApprenant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apprenant_has_cours_cours1`
    FOREIGN KEY (`cours_idCours`)
    REFERENCES `cours` (`idCours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resultat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resultat` (
  `idResultat` INT NOT NULL AUTO_INCREMENT,
  `valeur` DOUBLE NOT NULL,
  `valeursNormalles` DOUBLE NOT NULL,
  `apprenant_idApprenant` INT NOT NULL,
  `indicateur_nomIndicateur` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idResultat`),
  INDEX `fk_resultat_apprenant1_idx` (`apprenant_idApprenant` ASC),
  INDEX `fk_resultat_indicateur1_idx` (`indicateur_nomIndicateur` ASC),
  CONSTRAINT `fk_resultat_apprenant1`
    FOREIGN KEY (`apprenant_idApprenant`)
    REFERENCES `apprenant` (`idApprenant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resultat_indicateur1`
    FOREIGN KEY (`indicateur_nomIndicateur`)
    REFERENCES `indicateur` (`nomIndicateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trace_has_indicateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trace_has_indicateur` (
  `trace_idTrace` INT NOT NULL,
  `indicateur_nomIndicateur` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`trace_idTrace`, `indicateur_nomIndicateur`),
  INDEX `fk_trace_has_indicateur_indicateur1_idx` (`indicateur_nomIndicateur` ASC),
  INDEX `fk_trace_has_indicateur_trace1_idx` (`trace_idTrace` ASC),
  CONSTRAINT `fk_trace_has_indicateur_trace1`
    FOREIGN KEY (`trace_idTrace`)
    REFERENCES `trace` (`idTrace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trace_has_indicateur_indicateur1`
    FOREIGN KEY (`indicateur_nomIndicateur`)
    REFERENCES `indicateur` (`nomIndicateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
