-- MySQL Script generated by MySQL Workbench
-- Wed Aug 19 19:01:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `apprenant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apprenant` (
  `idApprenant` INT NOT NULL AUTO_INCREMENT,
  `nomApprenant` VARCHAR(50) NOT NULL,
  `prenomApprenant` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `mot_de_passe` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idApprenant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cours` (
  `idCours` INT NOT NULL AUTO_INCREMENT,
  `nomCours` VARCHAR(100) NOT NULL,
  `plateforme_url` VARCHAR(200) NOT NULL,
  `id_apprenant_plateforme` INT NOT NULL,
  PRIMARY KEY (`idCours`),
  UNIQUE INDEX `nomCours_UNIQUE` (`nomCours` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trace` (
  `idTrace` INT NOT NULL AUTO_INCREMENT,
  `nomTrace` VARCHAR(100) NOT NULL,
  `debut` DATETIME(6) NOT NULL,
  `fin` DATETIME(6) NOT NULL,
  `apprenant_idApprenant` INT NOT NULL,
  `cours_idCours` INT NOT NULL,
  PRIMARY KEY (`idTrace`),
  INDEX `fk_trace_apprenant1_idx` (`apprenant_idApprenant` ASC),
  INDEX `fk_trace_cours1_idx` (`cours_idCours` ASC),
  CONSTRAINT `fk_trace_apprenant1`
    FOREIGN KEY (`apprenant_idApprenant`)
    REFERENCES `apprenant` (`idApprenant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trace_cours1`
    FOREIGN KEY (`cours_idCours`)
    REFERENCES `cours` (`idCours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stratégie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stratégie` (
  `idStratégie` INT NOT NULL AUTO_INCREMENT,
  `nomStrategie` VARCHAR(100) NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idStratégie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indicateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indicateur` (
  `idIndicateur` INT NOT NULL AUTO_INCREMENT,
  `nomIndicateur` VARCHAR(100) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `valeur` DOUBLE NOT NULL,
  `valeursNormales` DOUBLE NOT NULL,
  `stratégie_idStratégie` INT NOT NULL,
  `apprenant_idApprenant` INT NOT NULL,
  PRIMARY KEY (`idIndicateur`),
  INDEX `fk_indicateur_stratégie1_idx` (`stratégie_idStratégie` ASC),
  INDEX `fk_indicateur_apprenant1_idx` (`apprenant_idApprenant` ASC),
  CONSTRAINT `fk_indicateur_stratégie1`
    FOREIGN KEY (`stratégie_idStratégie`)
    REFERENCES `stratégie` (`idStratégie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_indicateur_apprenant1`
    FOREIGN KEY (`apprenant_idApprenant`)
    REFERENCES `apprenant` (`idApprenant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `suggestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suggestion` (
  `idSuggestion` INT NOT NULL AUTO_INCREMENT,
  `methode` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idSuggestion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objectif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objectif` (
  `idObjectif` INT NOT NULL AUTO_INCREMENT,
  `idCours` INT NOT NULL,
  `idApprenant` INT NOT NULL,
  `descrip` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idObjectif`, `idCours`, `idApprenant`),
  INDEX `fk_apprenant_has_cours_cours1_idx` (`idCours` ASC),
  INDEX `fk_apprenant_has_cours_apprenant_idx` (`idObjectif` ASC),
  CONSTRAINT `fk_apprenant_has_cours_apprenant`
    FOREIGN KEY (`idObjectif`)
    REFERENCES `apprenant` (`idApprenant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apprenant_has_cours_cours1`
    FOREIGN KEY (`idCours`)
    REFERENCES `cours` (`idCours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trace_has_indicateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trace_has_indicateur` (
  `trace_idTrace` INT NOT NULL,
  `indicateur_idIndicateur` INT NOT NULL,
  PRIMARY KEY (`trace_idTrace`, `indicateur_idIndicateur`),
  INDEX `fk_trace_has_indicateur_indicateur1_idx` (`indicateur_idIndicateur` ASC),
  INDEX `fk_trace_has_indicateur_trace1_idx` (`trace_idTrace` ASC),
  CONSTRAINT `fk_trace_has_indicateur_trace1`
    FOREIGN KEY (`trace_idTrace`)
    REFERENCES `trace` (`idTrace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trace_has_indicateur_indicateur1`
    FOREIGN KEY (`indicateur_idIndicateur`)
    REFERENCES `indicateur` (`idIndicateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indicateur_has_suggestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indicateur_has_suggestion` (
  `indicateur_idIndicateur` INT NOT NULL,
  `suggestion_idSuggestion` INT NOT NULL,
  PRIMARY KEY (`indicateur_idIndicateur`, `suggestion_idSuggestion`),
  INDEX `fk_indicateur_has_suggestion_suggestion1_idx` (`suggestion_idSuggestion` ASC),
  INDEX `fk_indicateur_has_suggestion_indicateur1_idx` (`indicateur_idIndicateur` ASC),
  CONSTRAINT `fk_indicateur_has_suggestion_indicateur1`
    FOREIGN KEY (`indicateur_idIndicateur`)
    REFERENCES `indicateur` (`idIndicateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_indicateur_has_suggestion_suggestion1`
    FOREIGN KEY (`suggestion_idSuggestion`)
    REFERENCES `suggestion` (`idSuggestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cours_has_suggestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cours_has_suggestion` (
  `cours_idCours` INT NOT NULL,
  `suggestion_idSuggestion` INT NOT NULL,
  PRIMARY KEY (`cours_idCours`, `suggestion_idSuggestion`),
  INDEX `fk_cours_has_suggestion_suggestion1_idx` (`suggestion_idSuggestion` ASC),
  INDEX `fk_cours_has_suggestion_cours1_idx` (`cours_idCours` ASC),
  CONSTRAINT `fk_cours_has_suggestion_cours1`
    FOREIGN KEY (`cours_idCours`)
    REFERENCES `cours` (`idCours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cours_has_suggestion_suggestion1`
    FOREIGN KEY (`suggestion_idSuggestion`)
    REFERENCES `suggestion` (`idSuggestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
